assignment/config/routes.rb
Rails.application.routes.draw do
  # get 'blog_functions/index'

  # get 'blog_functions/new'

  # get 'blog_functions/create'

  # get 'blog_functions/show'

  # get 'blog_functions/edit'

  # get 'blog_functions/update'

  # get 'blog_functions/destroy'

  # get 'blogs_functions/index'

  # get 'blogs_functions/show'

  # get 'blogs_functions/edit'

  # get 'blogs_functions/update'

  # get 'blogs_functions/destroy'

  # get 'contacts/new'

  # get 'contacts/create'
  # resources :contacts 
  resources :blog_functions do
   collection do
      post :confirm
    end
  end
  # resources :blogs_functions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

assignment/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

assignment/app/models/blog_function.rb
class BlogFunction < ApplicationRecord
     validates :content, presence: true, length: { in: 1..140 }
end

assignment/app/models/contact.rb
class Contact < ApplicationRecord
    #  validates :name, presence: true
    #   validates :email, presence: true
    #   validates :content, presence: true
    validates :content, presence: true, length: { in: 1..140 }
    
end

assignment/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

assignment/app/controllers/blog_functions_controller.rb
class BlogFunctionsController < ApplicationController
   before_action :set_blog, only: [:show, :edit, :update, :destroy]
  def index
    @blog_functions = BlogFunction.all
  end

  def new
    if params[:back]
      @blog_function = BlogFunction.new(function_params)
    else
      @blog_function = BlogFunction.new
    end
  end
  
  
  def create
    @blog_function = BlogFunction.new(function_params)
    if @blog_function.save
      # Switch to the list screen and display a message saying "You have created new blog!"
      redirect_to blog_functions_path, notice: "You have created new blog_function!!!"
    else
      # Redraw the input form.
      render 'new'
    end
  end
  

  def show
    @blog_function = BlogFunction.find(params[:id])
  end


  def edit
     @blog_function = BlogFunction.find(params[:id])
  end


  def update
    @blog_function = BlogFunction.find(params[:id])
    if @blog_function.update(function_params)
      redirect_to blog_functions_path notice: 'you have updated this blog_function!!'
      else render 'edit'
    end
  end


  def destroy
    @blog_function.destroy
    redirect_to blog_functions_path notice: 'you have deleted one blog_function!!'
  end
  
  # def confirm
  #     @blog_function = BlogFunction.new(function_params)
  #   render :new if @blog_function.invalid?
  # end
  # end
  
  
  private
  def function_params
    params.require(:blog_function).permit(:name, :email, :content)
    
  end
  
   def set_blog
      @blog_function = BlogFunction.find(params[:id])
   end
end

assignment/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(name: params[:contact][:name], email: params[:contact][:email], content: params[:contact][:content])
    if  @contact.save
      redirect_to new_contact_path
    else render 'new'
   
    
    end
  end
end

assignment/app/helpers/application_helper.rb
module ApplicationHelper
end

assignment/app/helpers/blog_functions_helper.rb
module BlogFunctionsHelper
end

assignment/app/helpers/contacts_helper.rb
module ContactsHelper
end

assignment/app/views/blog_functions/create.html.erb
<h1>BlogFunctions#create</h1>
<p>Find me in app/views/blog_functions/create.html.erb</p>

assignment/app/views/blog_functions/edit.html.erb
<%= form_with(model: @blog_function, local: true ) do |form| %>
  <% if @blog_function.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog_function.errors.count %>errors occurred.</h2>
      <ul>

      <% @blog_function.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="function_name">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="function_name">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div class="function_name">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "Return to List of blog_functions ", blog_functions_path %>

assignment/app/views/blog_functions/index.html.erb
<h1>List of blog_functions</h1>
<p><%= notice %></p>
<table>
    <tr>
        <th> Name  </th>
        <th> Email  </th>
        <th> Content  </th>
    </tr>
    <% @blog_functions.each do |blog_function| %>
    <tr>
        <td><%= blog_function.name %></td>
        <td><%= blog_function.email %></td>
        <td><%= blog_function.content %></td>
        <td><%= link_to 'check blog_function details', blog_function_path(blog_function.id) %></td>
         <td><%= link_to 'edit blog_function', edit_blog_function_path(blog_function.id) %></td>
        <td><%= link_to "Delete blog", blog_function_path(blog_function.id), method: :delete ,data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
</table>
<br>
<%= link_to 'post a new blog_function', new_blog_function_path %>

assignment/app/views/blog_functions/new.html.erb
<%= form_with(model: @blog_function, local: true ) do |form| %>
  <% if @blog_function.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog_function.errors.count %>errors occurred.</h2>
      <ul>

      <% @blog_function.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="function_name">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="function_name">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>
  <div class="function_name">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "Return to List of blog_functions ", blog_functions_path %>

assignment/app/views/blog_functions/show.html.erb
<h1>BlogFunctions details</h1>
    <p>Name:<%= @blog_function.name %></p> 
    <p>Email:<%= @blog_function.email %></p>
    <p>Content:<%= @blog_function.content %></p>
    <br>
<%= link_to 'return to blog_functions',  blog_functions_path %>

assignment/app/views/contacts/create.html.erb
<h1>Contacts#create</h1>
<p>Find me in app/views/contacts/create.html.erb</p>

assignment/app/views/contacts/new.html.erb
<%= form_with(model: @contact, local: true ) do |form| %>
 <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "errors occurred") %></h2>
      <ul>

      <% @contact.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    <div class="contact_name">
        <%= form.label :name %>
        <%=form.text_field :name %>
    </div>
        
    <div class="contact_name">
         <%= form.label :email %>
        <%=form.text_field :email %>
    </div>
    
     <div class="contact_name">
         <%= form.label :content %>
        <%=form.text_field :content %>
    </div>
    <%= form.submit %>
<% end %>

assignment/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Assignment</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>